qemu sec gpio
Linaro/meta-ledge pull request #241
Opened 2021-01-28 10:10 UTC by muvarov

update qemu to mailine 5.2 and add secure gpio for reset/poweroff.

2021-01-28 10:13 UTC, apalos commented on meta-ledge-bsp/recipes-devtools/qemu/qemu.inc
> -	   file://find_datadir.patch \
All older patches are included in 5.2?

2021-01-28 10:13 UTC, apalos requested changes

2021-01-28 10:13 UTC, apalos commented on meta-ledge-bsp/recipes-bsp/trusted-firmware-a/trusted-firmware-a-ledge_git.bb
> +
I assume this hasn't been merged upstream yet?

2021-01-28 10:16 UTC, apalos commented on meta-ledge-bsp/recipes-devtools/qemu/qemu.inc
>  	   "
Are the qemu patrches merged in upstream? So this is a temporary patch until we get the next qemu version?

2021-01-28 10:18 UTC, apalos reviewed
From the commit message it's not clear why this is needed or if it's part of mainline QEMU.

If you reboot patches have been accepted in upstream, can you add something on the commit message that explains why we need those? I assume the patches are temporary until we bump our QEMU release?

2021-01-28 11:07 UTC, muvarov commented on meta-ledge-bsp/recipes-devtools/qemu/qemu.inc
>  	   "
Peter staged them to his qemu-arm branch. They have to be merged to qemu 6.0

2021-01-28 11:08 UTC, muvarov commented
Yes, this is temporary patch until qemu will release 6.0. This will take some time and we need fixed reboot now.

2021-02-09 16:44 UTC, apalos approved these changes

2021-02-10 06:52 UTC, muvarov commented
Merged with squash fix patch to the main patch.

2021-02-10 06:52 UTC, closed without merging