meta-ledge-bsp: Bump op-tee, u-boot and tf-a to latest stable master
Linaro/meta-ledge pull request #245
Opened 2021-02-25 19:06 UTC by apalos

Patch 1 Cleanup u-boot for stm32mp1 and apply patches for proper DACR configuration
Pathes 2/3: bump op-tee and TF-a to their latest stables tags

Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>

2021-02-25 21:10 UTC, muvarov commented
@apalos  Suggosh said me that efidebug syntax changed in the latest uboot. That means we need to update  BOOTCMD (auto boot uboot command.) We need to check that before the merge.

2021-02-25 21:12 UTC, muvarov requested changes
Patch "bsp: op-tee: Bump to 3.12" does not match description. And in general is not needed.

2021-02-25 21:19 UTC, apalos commented
> Patch "bsp: op-tee: Bump to 3.12" does not match description. And in general is not needed.

Oops, the wrong patch crept in there somehow

2021-02-25 21:19 UTC, muvarov commented on meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge_stm32mp157c_dk2_trusted_defconfig
> -CONFIG_CMD_BOOTEFI=y
please double check that options are not needed with updated uboot.

2021-02-25 21:23 UTC, apalos commented on meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge/ledge_stm32mp157c_dk2_trusted_defconfig
> -CONFIG_CMD_BOOTEFI=y
Those are now default for u-boot, they are still included in our build

2021-02-26 08:44 UTC, muvarov commented on meta-ledge-bsp/recipes-bsp/u-boot/u-boot-ledge.bb
> +    file://0003-ti-am572x-enable-boot_distrocmd.patch \
this patch is better to rename to 0000-ti-am...

2021-02-27 18:27 UTC, merged